services:
  - type: web
    name: easit-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --worker-class gthread --threads 10 --bind 0.0.0.0:$PORT main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
